---
apiVersion: 'nats.io/v1alpha2'
kind: 'NatsCluster'
metadata:
  name: 'nats-demo'
spec:
  size: 3
---
apiVersion: 'streaming.nats.io/v1alpha1'
kind: 'NatsStreamingCluster'
metadata:
  name: 'nats-demo-stan'
spec:
  size: 3
  natsSvc: 'nats-demo'
